version: 2

jobs:
  test:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/browsers:node12.18.0-chrome83-ff77'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: npx cypress verify    
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests
          command: npm run cy:ci
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  executetests:
    jobs:
      - test